spring:
  data:
    mongodb:
      host: 192.168.1.141
      port: 27017
      database: ecp
      username: ecp
      password: hiynn123456
  #ActiveMQ配置
  activemq:
    #前端地址 ws://192.168.1.22:61614/stomp
    broker-url: tcp://192.168.1.141:61616
    user: admin
    password: admin
    packages:
      trust-all: true

#  jms:
#    pub-sub-domain: true

image:
  path: /home/static/friend/image